name: Bump version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Dry run next version
        run: |
          DRY_RUN_OUTPUT=$(cz bump --dry-run)
          NEXT_VERSION=$(echo "$DRY_RUN_OUTPUT" | grep 'Bump version' | sed -E 's/.*to ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Update version file
        run: |
          if [ -f "src/version.py" ]; then
            sed -i "s/__version__ = .*/__version__ = \"${{ env.NEXT_VERSION }}\"/" src/version.py
          elif [ -f "src/release.ver" ]; then
            echo "${{ env.NEXT_VERSION }}" > src/release.ver
          fi
          git add .

      - name: Bump version
        run: |
          git config --local user.email "cwkim@deepx.ai"
          git config --local user.name "cwkimDO"
          cz bump --yes
          git push
          git push --tag



      - name: Print Version
        run: echo "Bumped to version ${{ env.NEXT_VERSION }}"