name: Versioning

on:
  push:
    branches:
      - dev
      - main

jobs:
  set-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version Info
        id: set-environment
        run: |
          if [ -f "release.ver" ]; then
            COMPILER_VERSION_PATH = "release.ver"
          else
            COMPILER_DIR=$(find ./src -type d -name "dx_*" | head -n 1)
            COMPILER_DIR_CLR=${COMPILER_DIR:6}
            COMPILER_VERSION_PATH=src/${COMPILER_DIR_CLR}/version.py
          fi
          echo "version_file_path: $COMPILER_VERSION_PATH"
          echo "version_file_path=$COMPILER_VERSION_PATH" >> $GITHUB_OUTPUT
    outputs:
      version_file_path: ${{ steps.set-environment.outputs.version_file_path }}

  bump-dev-version:
    needs: set-environment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          pip install bump2version git-changelog

      - name: Determine version
        id: version_info
        run: |
          version_file=${{ needs.set-environment.outputs.version_file_path }}
          current_version=$(sed -nE 's/^__version__ = "(.*)"/\1/p' "$version_file")
          new_version=$(bump2version --dry-run --list | grep current_version | sed 's/^.*=//').dev$(date +%s)

          echo "current: $current_version newe: $new_version"
          echo "current_version=$current_version" >> $GITHUB_OUTPUT
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Update version
        run: |
          bump2version --new-version ${{ steps.version_info.outputs.new_version }} ${{ needs.set-environment.outputs.version_file_path }}

      - name: Generate changelog
        run: |
          git-changelog --template changelog.md.j2 > CHANGELOG.md

      - name: Commit changes
        run: |
          git config --local user.email $USER_EMAIL
          git config --local user.name $USER_NAME
          git add  ${{ steps.version_info.outputs.version_file_path }} CHANGELOG.md
          git commit -m "Bump version: ${{ steps.version_info.outputs.current_version }} to ${{ steps.version_info.outputs.new_version }}"
          git push origin dev
        env:
          USER_EMAIL: cwkim@deepx.ai
          USER_NAME: cwkimDO

  bump-main-version:
    needs: set-environment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install version management tool
        run: pip install bump2version
      - name: Update version
        run: |
          bump2version patch --allow-dirty --commit --tag ${{ needs.set-environment.outputs.version_file_path }}
      - name: Tag version
        run: |
          git push --follow-tags
