name: Versioning

on:
  push:
    branches:
      - dev
      - main

env:
  USER_EMAIL: cwkim@deepx.ai
  USER_NAME: cwkimDO

permissions:
  contents: write

jobs:
  # set-environment:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Get version file path
  #       id: set-environment
  #       run: |
  #         if [ -f "release.ver" ]; then
  #           COMPILER_VERSION_PATH="release.ver"
  #         else
  #           COMPILER_DIR=$(find ./src -type d -name "dx_*" | head -n 1)
  #           COMPILER_DIR_CLR=${COMPILER_DIR:6}
  #           COMPILER_VERSION_PATH=src/${COMPILER_DIR_CLR}/version.py
  #         fi
  #         echo "version_file_path=$COMPILER_VERSION_PATH" >> $GITHUB_OUTPUT
  #   outputs:
  #     version_file_path: ${{ steps.set-environment.outputs.version_file_path }}

  bump-dev-version:
    # needs: set-environment
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          pip install bump2version

      - name: Get version
        run: |
          VERSION=$(grep 'current_version =' .bumpversion.cfg | cut -d ' ' -f 3)
          echo "CURRENT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Bump version
        id: version_info
        run: |
          NEW_VERSION=$(bump2version patch --no-commit --no-tag --list | grep new_version | sed -r 's/new_version=(.*)/\1/')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Create local tag on last Bump version commit
        id: find_commit
        run: |
          LAST_COMMIT_HASH=$(git log --format="%H %s" | grep -m 1 'Bump version:' | cut -d' ' -f1)
          echo "LAST_COMMIT_HASH=$LAST_COMMIT_HASH" >> $GITHUB_ENV
          echo "::set-output name=commit_hash::$LAST_COMMIT_HASH"

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          config_file: .changelog-config.yml
          release_version: $NEW_VERSION

      - name: Commit changes
        run: |
          git config --local user.email $USER_EMAIL
          git config --local user.name $USER_NAME
          git add .
          git commit -m "Bump version: $CURRENT_VERSION to $NEW_VERSION"
          git push

  # bump-main-version:

  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.10'

  #     - name: Install version management tool
  #       run: pip install bump2version

  #     - name: Update version
  #       run: |
  #         git config --local user.email $USER_EMAIL
  #         git config --local user.name $USER_NAME
  #         bump2version patch --allow-dirty

  #     - name: Tag version
  #       run: |
  #         git push --follow-tags
  #         git remote set-url origin https://actions:${{ secrets.GITHUB_TOKEN }}@github.com/cheolwonkim/test.git
