name: Bump version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Dry run next version
        run: |
          DRY_RUN_OUTPUT=$(cz bump --dry-run)
          NEXT_VERSION=$(echo "$DRY_RUN_OUTPUT" | grep 'Bump version' | sed -E 's/.*to ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Update version file
        run: |
          COMPILER_DIR=$(find ./src -type d -name "dx_*" | head -n 1)
          COMPILER_DIR_CLR=${COMPILER_DIR:6}
          COMPILER_VERSION_PATH=src/${COMPILER_DIR:6}/version.py
          if [ -f "$COMPILER_VERSION_PATH" ]; then
            sed -i "s/__version__ = .*/__version__ = \"${{ env.NEXT_VERSION }}\"/" $COMPILER_VERSION_PATH
          elif [ -f "release.ver" ]; then
            echo "${{ env.NEXT_VERSION }}" > release.ver
          fi
          git add .

      - name: Bump version
        run: |
          if [ -z "${{ secrets.USER_EMAIL }}" ] || [ -z "${{ secrets.USER_NAME }}" ]; then
            echo "Error: User email and name must be set in secrets!"
            exit 1
          fi
          git config --local user.email "${{ secrets.USER_EMAIL }}"
          git config --local user.name "${{ secrets.USER_NAME }}"
          cz bump --yes
          git push
          git push --tag



      - name: Print Version
        run: echo "Bumped to version ${{ env.NEXT_VERSION }}"