name: Bump version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Calculate next version
        id: next_version
        run: echo "::set-output name=version::$(cz bump --dry-run | grep 'bump:' | sed -E 's/.*→ (.*)/\1/')"

      - name: Print Version
        run: echo "Bumped to version ${{ steps.next_version.outputs.version }}"