name: Bump version

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  bump_version:
    if: "!startsWith(${{ github.event.head_commit.message }}, 'Bump version:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}