name: PR Title and Commit Messages Checker

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate PR Title
        id: title_check
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "Checking PR Title: $env.PR_TITLE"
          echo "PR_TITLE_PATTERN: ${{ env.PR_TITLE_PATTERN }}"
          echo "COMMIT_MESSAGE_PATTERN: $COMMIT_MESSAGE_PATTERN"

          if echo $PR_TITLE | grep -Pq $PR_TITLE_PATTERN; then
            echo "::set-output name=match::true"
          elif echo $PR_TITLE | grep -Pq $COMMIT_MESSAGE_PATTERN; then
            echo "::set-output name=match::true"
          else
            echo "::set-output name=match::false"
          fi
        env:
          PR_TITLE_PATTERN: ${{ env.PR_TITLE_PATTERN }}
          COMMIT_MESSAGE_PATTERN: ${{ env.COMMIT_MESSAGE_PATTERN }}

      - name: Final Check
        if: steps.title_check.outputs.match == 'false'
        run: |
          echo "PR Title does not match any required format"
          exit 1
