name: PR Title and Commit Messages Checker

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-messages:
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE_PATTERN: '^(fix|feat|docs|style|refactor|break|test|build|ci|bump|Bump version)(\([^\)]+\))?: .+$'
      PR_TITLE_PATTERN: '^(Fix|Feat|Hotfix)\/[^\s]+$'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate PR Title
        id: title_check
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "Checking PR Title: $PR_TITLE"
          echo "PR_TITLE_PATTERN: $PR_TITLE_PATTERN"
          echo "COMMIT_MESSAGE_PATTERN: $COMMIT_MESSAGE_PATTERN"

          if echo "$PR_TITLE" | grep -Eq "$PR_TITLE_PATTERN"; then
            echo "::set-output name=match::true"
          else
            echo "::set-output name=match::false"
          fi

      - name: Final Check
        if: steps.title_check.outputs.match == 'false'
        run: |
          echo "PR Title does not match any required format"
          exit 1
