name: PR Title Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate PR Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          COMMIT_MESSAGE_PATTERN: '^(fix|feat|docs|style|refactor|break|test|build|ci|bump|Bump version)(\([^\)]+\))?: .+$'
          PR_TITLE_PATTERN: '^(Fix|Feat|Hotfix)\/[^\s]+$'
        run: |
          echo "Checking PR Title: $PR_TITLE"
          echo "PR_TITLE_PATTERN: $PR_TITLE_PATTERN"
          echo "COMMIT_MESSAGE_PATTERN: $COMMIT_MESSAGE_PATTERN"

          if echo "$PR_TITLE" | grep -Pq "$PR_TITLE_PATTERN"; then
            echo "PR title matches required format."
          elif echo "$PR_TITLE" | grep -Pq "$COMMIT_MESSAGE_PATTERN"; then
            echo "PR title matches commit message format."
          else
            echo "PR Title does not match any required format."
            exit 1
          fi
