name: Commit Message Checker

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check message
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          COMMIT_MESSAGE_PATTERN: '^(fix|feat|docs|style|refactor|break|test|build|ci|bump|Bump version)(\([^\)]+\))?: .+$'
          PR_TITLE_PATTERN: '^(Fix|Feat|Hotfix)\/[^]+$'
          RELEASE_PATTERN: '^(Release)[^]+$'
        run: |
          echo "Checking PR Title: $PR_TITLE"
          echo "PR_TITLE_PATTERN: $PR_TITLE_PATTERN"
          echo "COMMIT_MESSAGE_PATTERN: $COMMIT_MESSAGE_PATTERN"

          if echo "$PR_TITLE" | grep -Pq "$PR_TITLE_PATTERN"; then
            echo "PR title matches required format."
          elif echo "$PR_TITLE" | grep -Pq "$COMMIT_MESSAGE_PATTERN"; then
            echo "PR title matches commit message format."
          elif echo "$PR_TITLE" | grep -Pq "$RELEASE_PATTERN"; then
            echo "PR title matches release format."
          else
            echo "PR Title does not match any required format."
            exit 1
          fi

          echo "Fetching PR commits..."
          PR_COMMITS_URL=${{ github.event.pull_request.commits_url }}
          echo "Commits URL: $PR_COMMITS_URL"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR_COMMITS_URL > commits.json
          jq -r '.[].commit.message' commits.json | while read commit_message; do
            echo "Checking commit message: $commit_message"
            if ! echo "$commit_message" | grep -Pq "$COMMIT_MESSAGE_PATTERN"; then
              echo "Commit message does not match the required format."
              exit 1
            fi
          done
          echo "All commit messages match the required format."
